name: booking_system_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 8.1.0

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # COMMON
  nb_utils: ^5.0.8
  google_fonts: ^4.0.3
  html: ^0.15.2
  http: ^0.13.5
  intl: ^0.18.0
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.10

  # FIREBASE
  firebase_core: ^2.9.0
  firebase_crashlytics: ^3.1.0
  firebase_auth: ^4.4.0
  firebase_storage: ^11.1.0
  firebase_remote_config: ^4.0.0
  cloud_firestore: ^4.5.0

  # PUSH NOTIFICATION
  onesignal_flutter: 3.4.1

  # STATE MANAGEMENT
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5

  # ICON
  flutter_vector_icons: ^2.0.0
  flutter_svg: ^2.0.4

  # IMAGE
  image_picker: ^0.8.7
  photo_view: ^0.14.0
  lottie: ^2.3.1

  # OTHER
  country_picker: 2.0.19
  flutter_custom_tabs: ^1.0.4
  permission_handler: ^10.2.0
  flutter_html: ^3.0.0-alpha.5
  firebase_pagination: ^3.0.0

  # SOCIAL LOGIN
  google_sign_in: ^6.0.2
  the_apple_sign_in: ^1.1.1

  # PAYMENT GATEWAYS
  razorpay_flutter: ^1.3.4
  flutterwave_standard: ^1.0.7
  flutter_stripe: ^9.0.0+1
  cinetpay: ^1.0.6
  #  flutter_braintree: ^3.0.0 Remove due to play store does not approving the app

  # MAP
  google_maps_flutter: ^2.2.5
  geolocator: ^9.0.2
  geocoding: ^2.1.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/
    - assets/flag/
    - assets/images/
    - assets/icons/
    - assets/lottie/

